# Generated by Django 3.0.5 on 2020-04-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharespace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Occupied'), (2, 'Empty')]),
        ),
    ]
